# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'NativeWallet' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeWallet
  pod 'SideMenu'

  target 'NativeWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeWalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
